---

- name: Install
  gather_facts: false
  hosts: all
  #  become: true
  #  Do not assume root, to execute playbooks over command bus
  connection: local
  tasks: 

    - name: install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
